from pydantic import BaseModel, ConfigDict # Imports BaseModel from Pydantic that we use to define data models for validation which ensures incoming data is the right kind like strings , floats and so on. 
from typing import  Optional # Imported to give typing support

# TÜREN SCHEMAS
# Creates a class that inherits from BaseModel and determines the TürBase model ensuring required fields are included and valid. 
class TürBase(BaseModel):
    mark_name: str # Required Mark Name
    richtung_name: str # Required Richtung Name
    hohe_name: str # Required Höhe name
    breite_name: str # Required Breite Name
    oberfläche_name: str # Required Oberfläche Name
    schlossart_name: str # Required Schlossart name
    description: Optional[str] = None # Optional description
 
# Creates a class that inherits everything from the TürBase Class and makes a new Tür
class CreateTür(TürBase):
    pass

# Creates a class that inherits everything from the TürBase Class and reads the question data but adds fields generated by the database
class ReadTür(TürBase):
    id: int # id Field Declared as an integer

    # Allows Object Relational Mapping to Pydantic conversion, populates from alias if needed and excludes None fields automatically in responses
    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# SPECIFICATION SCHEMAS
# MARK SCHEMAS
# Creates a class that inherits from BaseModel and determines the MarkBase model ensuring all required fields are included and valid. 
class MarkBase(BaseModel):
    name: str # Name Field Declared as a string
    description: Optional[str] = None # Optional description

# Creates a class that inherits everything from the MarkBase Class and makes a new Mark
class CreateMark(MarkBase):
    pass

# Creates a class that inherits everything from the MarkBase Class and reads the data but adds fields generated by the database
class ReadMark(MarkBase):
    id: int # id Field Declared as an integer

    # Allows Object Relational Mapping to Pydantic conversion, populates from alias if needed and excludes None fields automatically in responses
    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# RICHTUNG SCHEMAS
# Creates a class that inherits from BaseModel and determines the RichtungBase model ensuring all required fields are included and valid. 
class RichtungBase(BaseModel):
    name: str # Name Field Declared as a string
    kürzung: str # Kürzung Field Declared as a string
    description: Optional[str] = None # Optional description

# Creates a class that inherits everything from the RichtungBase Class and makes a new Richtung
class CreateRichtung(RichtungBase):
    pass

# Creates a class that inherits everything from the RichtungBase Class and reads the data but adds fields generated by the database
class ReadRichtung(RichtungBase):
    id: int # id Field Declared as an integer

    # Allows Object Relational Mapping to Pydantic conversion, populates from alias if needed and excludes None fields automatically in responses
    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# HÖHE SCHEMAS
# Creates a class that inherits from BaseModel and determines the HoheBase model ensuring all required fields are included and valid. 
class HöheBase(BaseModel):
    name: str # Name Field Declared as a string
    nummer: int # Nummer Field Declared as an integer
    description: Optional[str] = None # Optional description

# Creates a class that inherits everything from the HöheBase Class and makes a new Hohe
class CreateHöhe(HöheBase):
    pass

# Creates a class that inherits everything from the HöheBase Class and reads the data but adds fields generated by the database
class ReadHöhe(HöheBase):
    id: int # id Field Declared as an integer

    # Allows Object Relational Mapping to Pydantic conversion, populates from alias if needed and excludes None fields automatically in responses
    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# BREITE SCHEMAS
# Creates a class that inherits from BaseModel and determines the BreiteBase model ensuring all required fields are included and valid. 
class BreiteBase(BaseModel):
    name: str # Name Field Declared as a string
    nummer: int # Nummer Field Declared as an integer
    description: Optional[str] = None # Optional description

# Creates a class that inherits everything from the BreiteBase Class and makes a new Breite
class CreateBreite(BreiteBase):
    pass

# Creates a class that inherits everything from the BreiteBase Class and reads the data but adds fields generated by the database
class ReadBreite(BreiteBase):
    id: int # id Field Declared as an integer

    # Allows Object Relational Mapping to Pydantic conversion, populates from alias if needed and excludes None fields automatically in responses
    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# OBERFLÄCHE SCHEMAS
# Creates a class that inherits from BaseModel and determines the OberflächeBase model ensuring all required fields are included and valid. 
class OberflächeBase(BaseModel):
    name: str # Name Field Declared as a string
    description: Optional[str] = None # Optional description

# Creates a class that inherits everything from the ObeflächeBase Class and makes a new OBERFLÄCHE
class CreateOberfläche(OberflächeBase):
    pass

# Creates a class that inherits everything from the OberflächerBase Class and reads the data but adds fields generated by the database
class ReadOberfläche(OberflächeBase):
    id: int # id Field Declared as an integer

    # Allows Object Relational Mapping to Pydantic conversion, populates from alias if needed and excludes None fields automatically in responses
    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# SCHLOSSART SCHEMAS
# Creates a class that inherits from BaseModel and determines the SchlossartBase model ensuring all required fields are included and valid. 
class SchlossartBase(BaseModel):
    name: str # Name Field Declared as a string
    kürzung: str # Kürzung Field Declared as a string
    description: Optional[str] = None # Optional description

# Creates a class that inherits everything from the SchlossartBase Class and makes a new Schlossart
class CreateSchlossart(SchlossartBase):
    pass

# Creates a class that inherits everything from the SchlossartBase Class and reads the data but adds fields generated by the database
class ReadSchlossart(SchlossartBase):
    id: int # id Field Declared as an integer

    # Allows Object Relational Mapping to Pydantic conversion, populates from alias if needed and excludes None fields automatically in responses
    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)
