from pydantic import BaseModel, ConfigDict # Imports BaseModel from Pydantic that we use to define data models for validation which ensures incoming data is the right kind like strings , floats and so on. 
from typing import  Optional, List # Imported to give typing support

# TÜREN SCHEMAS
# Creates a class that inherits from BaseModel and determines the TürBase model ensuring required fields are included and valid. 
class TürBase(BaseModel):
    mark_name: str # Required Mark Name
    richtung_name: str # Required Richtung Name
    hohe_name: str # Required Höhe name
    breite_name: str # Required Breite Name
    oberfläche_name: str # Required Oberfläche Name
    schlossart_name: str # Required Schlossart name
    lagerort_name: str 
    gewicht: int | None = None
    description: Optional[str] = None # Optional description
 
# Creates a class that inherits everything from the TürBase Class and makes a new Tür
class CreateTür(TürBase):
    pass

# Creates a class that inherits everything from the TürBase Class and reads the question data but adds fields generated by the database
class ReadTür(TürBase):
    menge: int # Invetory check
    gewicht: int | None = None
    id: int # id Field Declared as an integer

class BulkCreateTüren(BaseModel):
    türen: List[CreateTür]

    # Allows Object Relational Mapping to Pydantic conversion, populates from alias if needed and excludes None fields automatically in responses
    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# ZARGEN SCHEMAS
class ZargeBase(BaseModel):
    mark_name: str
    richtung_name: str
    hohe_name: str
    breite_name: str
    wandstärke_name: str
    oberfläche_name: str
    zargenart_name: str
    lagerort_name: str
    gewicht: int | None = None
    description: Optional[str] = None

class CreateZarge(ZargeBase):
    pass

class ReadZarge(ZargeBase):
    menge: int
    id: int

class BulkCreateZargen(BaseModel):
    zargen: List[CreateZarge]

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)


# SPECIFICATION SCHEMAS
# MARK SCHEMAS
class MarkBase(BaseModel):
    name: str 
    description: Optional[str] = None 

class CreateMark(MarkBase):
    pass

class ReadMark(MarkBase):
    id: int 

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# RICHTUNG SCHEMAS
class RichtungBase(BaseModel):
    name: str 
    kürzung: str 
    description: Optional[str] = None 

class CreateRichtung(RichtungBase):
    pass

class ReadRichtung(RichtungBase):
    id: int # 

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# HÖHE SCHEMAS
class HöheBase(BaseModel):
    name: str 
    nummer: int 
    description: Optional[str] = None 

class CreateHöhe(HöheBase):
    pass

class ReadHöhe(HöheBase):
    id: int 

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# BREITE SCHEMAS
class BreiteBase(BaseModel):
    name: str 
    nummer: int 
    description: Optional[str] = None 

class CreateBreite(BreiteBase):
    pass

class ReadBreite(BreiteBase):
    id: int 

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# OBERFLÄCHE SCHEMAS
class OberflächeBase(BaseModel):
    name: str 
    description: Optional[str] = None 

class CreateOberfläche(OberflächeBase):
    pass

class ReadOberfläche(OberflächeBase):
    id: int 

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# SCHLOSSART SCHEMAS
class SchlossartBase(BaseModel):
    name: str 
    kürzung: str
    description: Optional[str] = None 

class CreateSchlossart(SchlossartBase):
    pass

class ReadSchlossart(SchlossartBase):
    id: int 

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# WANDSTÄRKE SCHEMAS
class WandstärkBase(BaseModel):
    name: str
    nummer: int
    description: Optional[str] = None

class CreateWandstärk(WandstärkBase):
    pass

class ReadWandstärk(WandstärkBase):
    id: int

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)


# ZARGENART SCHEMAS
class ZargenartBase(BaseModel):
    name: str
    kürzung: str
    description: Optional[str] = None

class CreateZargenart(ZargenartBase):
    pass

class ReadZargenart(ZargenartBase):
    id: int

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)


# KUNDEN SCHEMAS
class KundeBase(BaseModel):
    name: str 
    adresse: str 
    tel: int 
    email: Optional[str] = None 

class CreateKunde(KundeBase):
    pass

class ReadKunde(KundeBase):
    id: int

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)

# LAGERORTEN SCHEMAS
class LagerOrtBase(BaseModel):
    name: str 

class CreateLagerOrt(LagerOrtBase):
    pass

class ReadLagerOrt(LagerOrtBase):
    id: int

class BulkCreateLagerOrt(BaseModel):
    lagerorte: list[CreateLagerOrt]

    model_config = ConfigDict(from_attributes=True, populate_by_name=True, exclude_none=True)